environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc
    - TARGET: i686-pc-windows-msvc

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain nightly
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

build_script:
  - git submodule -q update --init

test_script:
  - SET RUST_BACKTRACE=1
  - cargo test --target %TARGET% --all -v
  - cargo test --release --target %TARGET% --all -v

cache:
  - C:\Users\appveyor\.cargo\registry
  - target
