language: rust
dist: trusty
sudo: false

cache: cargo

os:
  - linux
  - osx

rust:
- 1.20.0
- stable
- nightly

script:
  - cargo build --verbose
  - env RUST_BACKTRACE=1 cargo test --all -v
  - env RUST_BACKTRACE=1 cargo test --all -v --release

  - if [[ $TRAVIS_RUST_VERSION = nightly* ]]; then
      env RUST_BACKTRACE=1 cargo bench --no-run --features nightly;
    fi
